<?php

namespace Database\Seeders;

use App\Models\Vidhansabha;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class VidhansabhaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $vidhansabhas = [
            ['constituency_no' => 1, 'constituency_name' => 'Behat बेहट'],
            ['constituency_no' => 2, 'constituency_name' => 'Nakur नाकुर'],
            ['constituency_no' => 3, 'constituency_name' => 'Saharanpur Nagar सहारनपुर नगर'],
            ['constituency_no' => 4, 'constituency_name' => 'Saharanpur सहारनपुर'],
            ['constituency_no' => 5, 'constituency_name' => 'Deoband देवबंद'],
            ['constituency_no' => 6, 'constituency_name' => 'Rampur Maniharan रामपुर मनिहारान (एससी)'],
            ['constituency_no' => 7, 'constituency_name' => 'Gangoh गंगोह'],
            ['constituency_no' => 8, 'constituency_name' => 'Kairana कैराना'],
            ['constituency_no' => 9, 'constituency_name' => 'Thana Bhawan थाना भवन'],
            ['constituency_no' => 10, 'constituency_name' => 'Shamli शामली'],
            ['constituency_no' => 11, 'constituency_name' => 'Budhana Budhana'],
            ['constituency_no' => 12, 'constituency_name' => 'Charthawal चरथावल'],
            ['constituency_no' => 13, 'constituency_name' => 'Purqazi पुरकाज़ी (एससी)'],
            ['constituency_no' => 14, 'constituency_name' => 'Muzaffarnagar मुजफ्फरनगर'],
            ['constituency_no' => 15, 'constituency_name' => 'Khatauli खतौली'],
            ['constituency_no' => 16, 'constituency_name' => 'Meerapur मीरापुर'],
            ['constituency_no' => 17, 'constituency_name' => 'Najibabad नजीबाबाद'],
            ['constituency_no' => 18, 'constituency_name' => 'Nagina नगीना (एससी)'],
            ['constituency_no' => 19, 'constituency_name' => 'Barhapur बरहापुर'],
            ['constituency_no' => 20, 'constituency_name' => 'Dhampur धामपुर'],
            ['constituency_no' => 21, 'constituency_name' => 'Nehtaur नेहटौर (एससी)'],
            ['constituency_no' => 22, 'constituency_name' => 'Bijnor बिजनौर'],
            ['constituency_no' => 23, 'constituency_name' => 'Chandpur चांदपुर'],
            ['constituency_no' => 24, 'constituency_name' => 'Noorpur नूरपुर'],
            ['constituency_no' => 25, 'constituency_name' => 'Kanth कंठ'],
            ['constituency_no' => 26, 'constituency_name' => 'Thakurdwara ठाकुरद्वारा'],
            ['constituency_no' => 27, 'constituency_name' => 'Moradabad Rural मुरादाबाद ग्रामीण'],
            ['constituency_no' => 28, 'constituency_name' => 'Moradabad Nagar मुरादाबाद नगर'],
            ['constituency_no' => 29, 'constituency_name' => 'Kundarki कुंदरकी'],
            ['constituency_no' => 30, 'constituency_name' => 'Bilari बिलारी'],
            ['constituency_no' => 31, 'constituency_name' => 'Chandausi चंदौसी (एससी)'],
            ['constituency_no' => 32, 'constituency_name' => 'Asmoli असमोली'],
            ['constituency_no' => 33, 'constituency_name' => 'Sambhal संभल'],
            ['constituency_no' => 34, 'constituency_name' => 'Suar सुअर'],
            ['constituency_no' => 35, 'constituency_name' => 'Chamraua चमरौआ'],
            ['constituency_no' => 36, 'constituency_name' => 'Bilaspur बिलासपुर'],
            ['constituency_no' => 37, 'constituency_name' => 'Rampur रामपुर'],
            ['constituency_no' => 38, 'constituency_name' => 'Milak मिलक (SC)'],
            ['constituency_no' => 39, 'constituency_name' => 'Dhanaura धनौरा (एससी)'],
            ['constituency_no' => 40, 'constituency_name' => 'Naugawan Sadat नौगावां सादात'],
            ['constituency_no' => 41, 'constituency_name' => 'Amroha अमरोहा'],
            ['constituency_no' => 42, 'constituency_name' => 'Hasanpur हसनपुर'],
            ['constituency_no' => 43, 'constituency_name' => 'Siwalkhas सिवालखास'],
            ['constituency_no' => 44, 'constituency_name' => 'Sardhana सरधना'],
            ['constituency_no' => 45, 'constituency_name' => 'Hastinapur हस्तिनापुर'],
            ['constituency_no' => 46, 'constituency_name' => 'Kithore किठौर'],
            ['constituency_no' => 47, 'constituency_name' => 'Meerut Cantt. मेरठ कैंट.'],
            ['constituency_no' => 48, 'constituency_name' => 'Meerut मेरठ शहर'],
            ['constituency_no' => 49, 'constituency_name' => 'Meerut South मेरठ दक्षिण'],
            ['constituency_no' => 50, 'constituency_name' => 'Chhaprauli Chhaprauli'],
            ['constituency_no' => 51, 'constituency_name' => 'Baraut बड़ौत'],
            ['constituency_no' => 52, 'constituency_name' => 'Bagpat बागपत'],
            ['constituency_no' => 53, 'constituency_name' => 'Loni लोनी'],
            ['constituency_no' => 54, 'constituency_name' => 'Muradnagar मुरादनगर'],
            ['constituency_no' => 55, 'constituency_name' => 'Sahibabad साहिबाबाद'],
            ['constituency_no' => 56, 'constituency_name' => 'Ghaziabad गाजियाबाद'],
            ['constituency_no' => 57, 'constituency_name' => 'Modinagar मोदी नगर'],
            ['constituency_no' => 58, 'constituency_name' => 'Dhaulana धौलाना'],
            ['constituency_no' => 59, 'constituency_name' => 'Hapur हापुड़'],
            ['constituency_no' => 60, 'constituency_name' => 'Garhmukteshwar गढ़मुक्तेश्वर'],
            ['constituency_no' => 61, 'constituency_name' => 'Noida नोएडा'],
            ['constituency_no' => 62, 'constituency_name' => 'Dadri दादरी'],
            ['constituency_no' => 63, 'constituency_name' => 'Jewar जेवर'],
            ['constituency_no' => 64, 'constituency_name' => 'Sikandrabad सिकंदराबाद'],
            ['constituency_no' => 65, 'constituency_name' => 'Bulandshahr बुलंदशहर'],
            ['constituency_no' => 66, 'constituency_name' => 'Syana स्याना'],
            ['constituency_no' => 67, 'constituency_name' => 'Anupshahr अनूपशहर'],
            ['constituency_no' => 68, 'constituency_name' => 'Debai डिबाई'],
            ['constituency_no' => 69, 'constituency_name' => 'Shikarpur शिकारपुर'],
            ['constituency_no' => 70, 'constituency_name' => 'Khurja खुर्जा (एससी)'],
            ['constituency_no' => 71, 'constituency_name' => 'Khair खैर (एससी)'],
            ['constituency_no' => 72, 'constituency_name' => 'Barauli बरौली'],
            ['constituency_no' => 73, 'constituency_name' => 'Atrauli अतरौली'],
            ['constituency_no' => 74, 'constituency_name' => 'Chharra छर्रा'],
            ['constituency_no' => 75, 'constituency_name' => 'Koil कोइल'],
            ['constituency_no' => 76, 'constituency_name' => 'Aligarh अलीगढ़'],
            ['constituency_no' => 77, 'constituency_name' => 'Iglas इग्लास (SC)'],
            ['constituency_no' => 78, 'constituency_name' => 'Hathras हाथरस (एससी)'],
            ['constituency_no' => 79, 'constituency_name' => 'Sadabad सादाबाद'],
            ['constituency_no' => 80, 'constituency_name' => 'Sikandra Rao सिकंदरा राव'],
            ['constituency_no' => 81, 'constituency_name' => 'Chhata छत्ता'],
            ['constituency_no' => 82, 'constituency_name' => 'Mant मंट'],
            ['constituency_no' => 83, 'constituency_name' => 'Goverdhan गोवर्धन'],
            ['constituency_no' => 84, 'constituency_name' => 'Mathura मथुरा'],
            ['constituency_no' => 85, 'constituency_name' => 'Baldev बलदेव (एससी)'],
            ['constituency_no' => 86, 'constituency_name' => 'Etmadpur एतमादपुर'],
            ['constituency_no' => 87, 'constituency_name' => 'Agra Cantt. आगरा कैंट (एससी)'],
            ['constituency_no' => 88, 'constituency_name' => 'Agra South आगरा दक्षिण'],
            ['constituency_no' => 89, 'constituency_name' => 'Agra North आगरा उत्तर'],
            ['constituency_no' => 90, 'constituency_name' => 'Agra Rural आगरा ग्रामीण (एससी)'],
            ['constituency_no' => 91, 'constituency_name' => 'Fatehpur Sikri फतेहपुर सीकरी'],
            ['constituency_no' => 92, 'constituency_name' => 'Kheragarh खेरागढ़'],
            ['constituency_no' => 93, 'constituency_name' => 'Fatehabad फतेहाबाद'],
            ['constituency_no' => 94, 'constituency_name' => 'Bah बाह'],
            ['constituency_no' => 95, 'constituency_name' => 'Tundla टूंडला (एससी)'],
            ['constituency_no' => 96, 'constituency_name' => 'Jasrana जसराना'],
            ['constituency_no' => 97, 'constituency_name' => 'Firozabad फिरोजाबाद'],
            ['constituency_no' => 98, 'constituency_name' => 'Shikohabad शिकोहाबाद'],
            ['constituency_no' => 99, 'constituency_name' => 'Sirsaganj सिरसागंज'],
            ['constituency_no' => 100, 'constituency_name' => 'Kasganj कासगंज'],
            ['constituency_no' => 101, 'constituency_name' => 'Amanpur अमनपुर'],
            ['constituency_no' => 102, 'constituency_name' => 'Patiyali पटियाली'],
            ['constituency_no' => 103, 'constituency_name' => 'Aliganj अलीगंज'],
            ['constituency_no' => 104, 'constituency_name' => 'Etah एटा'],
            ['constituency_no' => 105, 'constituency_name' => 'Marhara मारहारा'],
            ['constituency_no' => 106, 'constituency_name' => 'Jalesar जलेसर (एससी)'],
            ['constituency_no' => 107, 'constituency_name' => 'Mainpuri मैनपुरी'],
            ['constituency_no' => 108, 'constituency_name' => 'Bhongaon भोंगांव'],
            ['constituency_no' => 109, 'constituency_name' => 'Kishni किशनी (एससी)'],
            ['constituency_no' => 110, 'constituency_name' => 'Karhal करहल'],
            ['constituency_no' => 111, 'constituency_name' => 'Gunnaur गुन्नौर'],
            ['constituency_no' => 112, 'constituency_name' => 'Bisauli बिसौली (एससी)'],
            ['constituency_no' => 113, 'constituency_name' => 'Sahaswan सहसवान'],
            ['constituency_no' => 114, 'constituency_name' => 'Bilsi बिल्सी'],
            ['constituency_no' => 115, 'constituency_name' => 'Badaun बदायूं'],
            ['constituency_no' => 116, 'constituency_name' => 'Shekhupur शेखूपुर'],
            ['constituency_no' => 117, 'constituency_name' => 'Dataganj दातागंज'],
            ['constituency_no' => 118, 'constituency_name' => 'Baheri बहेरी'],
            ['constituency_no' => 119, 'constituency_name' => 'Meerganj मीरगंज'],
            ['constituency_no' => 120, 'constituency_name' => 'Bhojipura भोजीपुरा'],
            ['constituency_no' => 121, 'constituency_name' => 'Nawabganj नवाबगंज'],
            ['constituency_no' => 122, 'constituency_name' => 'Faridpur फरीदपुर (एससी)'],
            ['constituency_no' => 123, 'constituency_name' => 'Bithari Chainpur बिथरी चैनपुर'],
            ['constituency_no' => 124, 'constituency_name' => 'Bareilly बरेली'],
            ['constituency_no' => 125, 'constituency_name' => 'Bareilly Cantt. बरेली कैंट'],
            ['constituency_no' => 126, 'constituency_name' => 'Aonla आंवला'],
            ['constituency_no' => 127, 'constituency_name' => 'Pilibhit पीलीभीत'],
            ['constituency_no' => 128, 'constituency_name' => 'Barkhera बरखेड़ा'],
            ['constituency_no' => 129, 'constituency_name' => 'Puranpur पूरनपुर (एससी)'],
            ['constituency_no' => 130, 'constituency_name' => 'Bisalpur बीसलपुर'],
            ['constituency_no' => 131, 'constituency_name' => 'Katra कटरा'],
            ['constituency_no' => 132, 'constituency_name' => 'Jalalabad जलालाबाद'],
            ['constituency_no' => 133, 'constituency_name' => 'Tilhar तिलहर'],
            ['constituency_no' => 134, 'constituency_name' => 'Powayan पोवायन (एससी)'],
            ['constituency_no' => 135, 'constituency_name' => 'Shahjahanpur शाहजहांपुर'],
            ['constituency_no' => 136, 'constituency_name' => 'Dadraul दादरौल'],
            ['constituency_no' => 137, 'constituency_name' => 'Palia पलिया'],
            ['constituency_no' => 138, 'constituency_name' => 'Nighasan निघासन'],
            ['constituency_no' => 139, 'constituency_name' => 'Gola Gokrannath गोला गोकर्णनाथ'],
            ['constituency_no' => 140, 'constituency_name' => 'Sri Nagar श्री नगर (एससी)'],
            ['constituency_no' => 141, 'constituency_name' => 'Dhaurahra धौरहरा'],
            ['constituency_no' => 142, 'constituency_name' => 'Lakhimpur लखीमपुर'],
            ['constituency_no' => 143, 'constituency_name' => 'Kasta कस्ता (एससी)'],
            ['constituency_no' => 144, 'constituency_name' => 'Mohammdi मोहम्मदी'],
            ['constituency_no' => 145, 'constituency_name' => 'Maholi महोली'],
            ['constituency_no' => 146, 'constituency_name' => 'Sitapur सीतापुर'],
            ['constituency_no' => 147, 'constituency_name' => 'Hargaon हरगांव (एससी)'],
            ['constituency_no' => 148, 'constituency_name' => 'Laharpur लहरपुर'],
            ['constituency_no' => 149, 'constituency_name' => 'Biswan बिसवां'],
            ['constituency_no' => 150, 'constituency_name' => 'Sevata सेवता'],
            ['constituency_no' => 151, 'constituency_name' => 'Mahmoodabad महमूदाबाद'],
            ['constituency_no' => 152, 'constituency_name' => 'Sidhauli सिधौली (एससी)'],
            ['constituency_no' => 153, 'constituency_name' => 'Misrikh मिसरिख (एससी)'],
            ['constituency_no' => 154, 'constituency_name' => 'Sawayazpur सवायजपुर'],
            ['constituency_no' => 155, 'constituency_name' => 'Shahabad शाहाबाद'],
            ['constituency_no' => 156, 'constituency_name' => 'Hardoi हरदोई'],
            ['constituency_no' => 157, 'constituency_name' => 'Gopamau गोपामऊ (एससी)'],
            ['constituency_no' => 158, 'constituency_name' => 'Sandi सैंडी (एससी)'],
            ['constituency_no' => 159, 'constituency_name' => 'Bilgram-Mallanwan बिलग्राम-मल्लानवां'],
            ['constituency_no' => 160, 'constituency_name' => 'Balamau बालामऊ (एससी)'],
            ['constituency_no' => 161, 'constituency_name' => 'Sandila संडीला'],
            ['constituency_no' => 162, 'constituency_name' => 'Bangarmau बांगरमऊ'],
            ['constituency_no' => 163, 'constituency_name' => 'Safipur सफीपुर (एससी)'],
            ['constituency_no' => 164, 'constituency_name' => 'Mohan मोहन (एससी)'],
            ['constituency_no' => 165, 'constituency_name' => 'Unnao उन्नाव'],
            ['constituency_no' => 166, 'constituency_name' => 'Bhagwantnagar भगवंतनगर'],
            ['constituency_no' => 167, 'constituency_name' => 'Purwa पूर्वा'],
            ['constituency_no' => 168, 'constituency_name' => 'Malihabad मलीहाबाद (एससी)'],
            ['constituency_no' => 169, 'constituency_name' => 'Bakshi Kaa Talab बख्शी का तालाब'],
            ['constituency_no' => 170, 'constituency_name' => 'Sarojini Nagar सरोजिनी नगर'],
            ['constituency_no' => 171, 'constituency_name' => 'Lucknow West लखनऊ पश्चिम'],
            ['constituency_no' => 172, 'constituency_name' => 'Lucknow North लखनऊ उत्तर'],
            ['constituency_no' => 173, 'constituency_name' => 'Lucknow East लखनऊ पूर्व'],
            ['constituency_no' => 174, 'constituency_name' => 'Lucknow Central लखनऊ सेंट्रल'],
            ['constituency_no' => 175, 'constituency_name' => 'Lucknow Cantonment लखनऊ कैंट'],
            ['constituency_no' => 176, 'constituency_name' => 'Mohanlalganj मोहनलालगंज (एससी)'],
            ['constituency_no' => 177, 'constituency_name' => 'Bachhrawan बछरावां (एससी)'],
            ['constituency_no' => 178, 'constituency_name' => 'Tiloi तिलोई'],
            ['constituency_no' => 179, 'constituency_name' => 'Harchandpur हरचंदपुर'],
            ['constituency_no' => 180, 'constituency_name' => 'Rae Bareli रायबरेली'],
            ['constituency_no' => 181, 'constituency_name' => 'Salon सैलून (एससी)'],
            ['constituency_no' => 182, 'constituency_name' => 'Sareni सारेनी'],
            ['constituency_no' => 183, 'constituency_name' => 'Unchahar ऊंचाहार'],
            ['constituency_no' => 184, 'constituency_name' => 'Jagdishpur जगदीशपुर (एससी)'],
            ['constituency_no' => 185, 'constituency_name' => 'Gauriganj गौरीगंज'],
            ['constituency_no' => 186, 'constituency_name' => 'Amethi अमेठी'],
            ['constituency_no' => 187, 'constituency_name' => 'Isauli इसौली'],
            ['constituency_no' => 188, 'constituency_name' => 'Sultanpur सुल्तानपुर'],
            ['constituency_no' => 189, 'constituency_name' => 'Sultanpur Sadar सदर'],
            ['constituency_no' => 190, 'constituency_name' => 'Lambhua लम्भुआ'],
            ['constituency_no' => 191, 'constituency_name' => 'Kadipur कादीपुर (एससी)'],
            ['constituency_no' => 192, 'constituency_name' => 'Kaimganj कायमगंज (एससी)'],
            ['constituency_no' => 193, 'constituency_name' => 'Amritpur अमृतपुर'],
            ['constituency_no' => 194, 'constituency_name' => 'Farrukhabad फर्रुखाबाद'],
            ['constituency_no' => 195, 'constituency_name' => 'Bhojpur भोजपुर'],
            ['constituency_no' => 196, 'constituency_name' => 'Chhibramau छिबरामऊ'],
            ['constituency_no' => 197, 'constituency_name' => 'Tirwa तिर्वा'],
            ['constituency_no' => 198, 'constituency_name' => 'Kannauj कन्नौज (एससी)'],
            ['constituency_no' => 199, 'constituency_name' => 'Jaswantnagar जसवंतनगर'],
            ['constituency_no' => 200, 'constituency_name' => 'Etawah इटावा'],
            ['constituency_no' => 201, 'constituency_name' => 'Bharthana भरथना (एससी)'],
            ['constituency_no' => 202, 'constituency_name' => 'Bidhuna बिधूना'],
            ['constituency_no' => 203, 'constituency_name' => 'Dibiyapur दिबियापुर'],
            ['constituency_no' => 204, 'constituency_name' => 'Auraiya औरैया (एससी)'],
            ['constituency_no' => 205, 'constituency_name' => 'Rasulabad रसूलाबाद (एससी)'],
            ['constituency_no' => 206, 'constituency_name' => 'Akbarpur-Raniya अकबरपुर-रानियां'],
            ['constituency_no' => 207, 'constituency_name' => 'Sikandra सिकंदरा'],
            ['constituency_no' => 208, 'constituency_name' => 'Bhognipur भोगनीपुर'],
            ['constituency_no' => 209, 'constituency_name' => 'Bilhaur बिल्हौर (एससी)'],
            ['constituency_no' => 210, 'constituency_name' => 'Bithoor बिठूर'],
            ['constituency_no' => 211, 'constituency_name' => 'Kalyanpur कल्याणपुर'],
            ['constituency_no' => 212, 'constituency_name' => 'Govind Nagar गोविंदनगर'],
            ['constituency_no' => 213, 'constituency_name' => 'Sishamau शीशमऊ'],
            ['constituency_no' => 214, 'constituency_name' => 'Arya Nagar आर्य नगर'],
            ['constituency_no' => 215, 'constituency_name' => 'Kidwai Nagar किदवई नगर'],
            ['constituency_no' => 216, 'constituency_name' => 'Kanpur Cantonment कानपुर कैंट'],
            ['constituency_no' => 217, 'constituency_name' => 'Maharajpur महाराजपुर'],
            ['constituency_no' => 218, 'constituency_name' => 'Ghatampur घाटमपुर (एससी)'],
            ['constituency_no' => 219, 'constituency_name' => 'Madhogarh माधौगढ़'],
            ['constituency_no' => 220, 'constituency_name' => 'Kalpi कालपी'],
            ['constituency_no' => 221, 'constituency_name' => 'Orai ओराई (एससी)'],
            ['constituency_no' => 222, 'constituency_name' => 'Babina बबीना'],
            ['constituency_no' => 223, 'constituency_name' => 'Jhansi Nagar झांसी नगर'],
            ['constituency_no' => 224, 'constituency_name' => 'Mauranipur मऊरानीपुर (एससी)'],
            ['constituency_no' => 225, 'constituency_name' => 'Garautha गरौथा'],
            ['constituency_no' => 226, 'constituency_name' => 'Lalitpur Lalitpur'],
            ['constituency_no' => 227, 'constituency_name' => 'Mehroni मेहरौनी (एससी)'],
            ['constituency_no' => 228, 'constituency_name' => 'Hamirpur हमीरपुर'],
            ['constituency_no' => 229, 'constituency_name' => 'Rath रथ (एससी)'],
            ['constituency_no' => 230, 'constituency_name' => 'Mahoba महोबा'],
            ['constituency_no' => 231, 'constituency_name' => 'Charkhari चरखारी'],
            ['constituency_no' => 232, 'constituency_name' => 'Tindwari तिंदवारी'],
            ['constituency_no' => 233, 'constituency_name' => 'Baberu बबेरू'],
            ['constituency_no' => 234, 'constituency_name' => 'Naraini नारायणी (एससी)'],
            ['constituency_no' => 235, 'constituency_name' => 'Banda बाँदा'],
            ['constituency_no' => 236, 'constituency_name' => 'Chitrakoot चित्रकूट'],
            ['constituency_no' => 237, 'constituency_name' => 'Manikpur मानिकपुर'],
            ['constituency_no' => 238, 'constituency_name' => 'Jahanabad जहानाबाद'],
            ['constituency_no' => 239, 'constituency_name' => 'Bindki बिंदकी'],
            ['constituency_no' => 240, 'constituency_name' => 'Fatehpur फतेहपुर'],
            ['constituency_no' => 241, 'constituency_name' => 'Ayah Shah अयाह शाह'],
            ['constituency_no' => 242, 'constituency_name' => 'Husainganj हुसैनगंज'],
            ['constituency_no' => 243, 'constituency_name' => 'Khaga खागा (एससी)'],
            ['constituency_no' => 244, 'constituency_name' => 'Rampur Khas रामपुर खास'],
            ['constituency_no' => 245, 'constituency_name' => 'Babaganj बाबागंज (एससी)'],
            ['constituency_no' => 246, 'constituency_name' => 'Kunda कुंदा'],
            ['constituency_no' => 247, 'constituency_name' => 'Vishwanathganj विश्वनाथगंज'],
            ['constituency_no' => 248, 'constituency_name' => 'Pratapgarh प्रतापगढ़'],
            ['constituency_no' => 249, 'constituency_name' => 'Patti पट्टी'],
            ['constituency_no' => 250, 'constituency_name' => 'Raniganj रानीगंज'],
            ['constituency_no' => 251, 'constituency_name' => 'Sirathu सिराथू'],
            ['constituency_no' => 252, 'constituency_name' => 'Manjhanpur मंझनपुर (एससी)'],
            ['constituency_no' => 253, 'constituency_name' => 'Chail चैल'],
            ['constituency_no' => 254, 'constituency_name' => 'Phaphamau फाफामाऊ'],
            ['constituency_no' => 255, 'constituency_name' => 'Soraon सोरांव (एससी)'],
            ['constituency_no' => 256, 'constituency_name' => 'Phulpur फूलपुर'],
            ['constituency_no' => 257, 'constituency_name' => 'Pratappur प्रतापपुर'],
            ['constituency_no' => 258, 'constituency_name' => 'Handia हंडिया'],
            ['constituency_no' => 259, 'constituency_name' => 'Meja मेजा'],
            ['constituency_no' => 260, 'constituency_name' => 'Karachhana करछना'],
            ['constituency_no' => 261, 'constituency_name' => 'Allahabad West प्रयागराज पश्चिम'],
            ['constituency_no' => 262, 'constituency_name' => 'Allahabad North प्रयागराज उत्तर'],
            ['constituency_no' => 263, 'constituency_name' => 'Allahabad South प्रयागराज दक्षिण'],
            ['constituency_no' => 264, 'constituency_name' => 'Bara बारा (एससी)'],
            ['constituency_no' => 265, 'constituency_name' => 'Koraon कोरॉव'],
            ['constituency_no' => 266, 'constituency_name' => 'Kursi कुर्सी'],
            ['constituency_no' => 267, 'constituency_name' => 'Ram Nagar राम नगर'],
            ['constituency_no' => 268, 'constituency_name' => 'Barabanki बाराबंकी'],
            ['constituency_no' => 269, 'constituency_name' => 'Zaidpur जैदपुर (एससी)'],
            ['constituency_no' => 270, 'constituency_name' => 'Dariyabad दरियाबाद'],
            ['constituency_no' => 271, 'constituency_name' => 'Rudauli रुदौली'],
            ['constituency_no' => 272, 'constituency_name' => 'Haidergarh हैदरगढ़ (एससी)'],
            ['constituency_no' => 273, 'constituency_name' => 'Milkipur मिल्कीपुर (एससी)'],
            ['constituency_no' => 274, 'constituency_name' => 'Bikapur बीकापुर'],
            ['constituency_no' => 275, 'constituency_name' => 'Ayodhya अयोध्या'],
            ['constituency_no' => 276, 'constituency_name' => 'Goshainganj गोशाईगंज'],
            ['constituency_no' => 277, 'constituency_name' => 'Katehari कटेहारी'],
            ['constituency_no' => 278, 'constituency_name' => 'Tanda टांडा'],
            ['constituency_no' => 279, 'constituency_name' => 'Alapur अलापुर (एससी)'],
            ['constituency_no' => 280, 'constituency_name' => 'Jalalpur जलालपुर'],
            ['constituency_no' => 281, 'constituency_name' => 'Akbarpur अकबरपुर'],
            ['constituency_no' => 282, 'constituency_name' => 'Balha बल्हा (एससी)'],
            ['constituency_no' => 283, 'constituency_name' => 'Nanpara नानपारा'],
            ['constituency_no' => 284, 'constituency_name' => 'Matera मटेरा'],
            ['constituency_no' => 285, 'constituency_name' => 'Mahasi महासी'],
            ['constituency_no' => 286, 'constituency_name' => 'Bahraich बहराइच'],
            ['constituency_no' => 287, 'constituency_name' => 'Payagpur पयागपुर'],
            ['constituency_no' => 288, 'constituency_name' => 'Kaiserganj कैसरगंज'],
            ['constituency_no' => 289, 'constituency_name' => 'Bhinga भिनगा'],
            ['constituency_no' => 290, 'constituency_name' => 'Shrawasti श्रावस्ती'],
            ['constituency_no' => 291, 'constituency_name' => 'Tulsipur तुलसीपुर'],
            ['constituency_no' => 292, 'constituency_name' => 'Gainsari गेंसारी'],
            ['constituency_no' => 293, 'constituency_name' => 'Utraula उतरौला'],
            ['constituency_no' => 294, 'constituency_name' => 'Balrampur बलरामपुर (एससी)'],
            ['constituency_no' => 295, 'constituency_name' => 'Mehnaun मेहनौन'],
            ['constituency_no' => 296, 'constituency_name' => 'Gonda गोंडा'],
            ['constituency_no' => 297, 'constituency_name' => 'Katra Bazar कटरा बाजार'],
            ['constituency_no' => 298, 'constituency_name' => 'Colonelganj कर्नलगंज'],
            ['constituency_no' => 299, 'constituency_name' => 'Tarabganj तरबगंज'],
            ['constituency_no' => 300, 'constituency_name' => 'Mankapur मनकापुर (एससी)'],
            ['constituency_no' => 301, 'constituency_name' => 'Gaura गौर'],
            ['constituency_no' => 302, 'constituency_name' => 'Shohratgarh शोहरतगढ़'],
            ['constituency_no' => 303, 'constituency_name' => 'Kapilvastu कपिलवस्तु (SC)'],
            ['constituency_no' => 304, 'constituency_name' => 'Bansi बंसी'],
            ['constituency_no' => 305, 'constituency_name' => 'Itwa यह वा'],
            ['constituency_no' => 306, 'constituency_name' => 'Domariyaganj डुमरियागंज लोक सभा निर्वाचन क्षेत्र'],
            ['constituency_no' => 307, 'constituency_name' => 'Harraiya हर्रैया'],
            ['constituency_no' => 308, 'constituency_name' => 'Kaptanganj कप्तानगंज'],
            ['constituency_no' => 309, 'constituency_name' => 'Rudhauli रुधौली'],
            ['constituency_no' => 310, 'constituency_name' => 'Basti Sadar बस्ती सदर'],
            ['constituency_no' => 311, 'constituency_name' => 'Mahadewa महादेवा (एससी)'],
            ['constituency_no' => 312, 'constituency_name' => 'Menhdawal मेंहदावल'],
            ['constituency_no' => 313, 'constituency_name' => 'Khalilabad खलीलाबाद'],
            ['constituency_no' => 314, 'constituency_name' => 'Dhanghata धनघटा (एससी)'],
            ['constituency_no' => 315, 'constituency_name' => 'Pharenda फरेंदा'],
            ['constituency_no' => 316, 'constituency_name' => 'Nautanwa नौतनवा'],
            ['constituency_no' => 317, 'constituency_name' => 'Siswa सिसवा'],
            ['constituency_no' => 318, 'constituency_name' => 'Maharajganj महाराजगंज (एससी)'],
            ['constituency_no' => 319, 'constituency_name' => 'Paniyara पनियारा'],
            ['constituency_no' => 320, 'constituency_name' => 'Caimpiyarganj कैम्पियारगंज'],
            ['constituency_no' => 321, 'constituency_name' => 'Pipraich पिपराइच'],
            ['constituency_no' => 322, 'constituency_name' => 'Gorakhpur Urban गोरखपुर शहरी'],
            ['constituency_no' => 323, 'constituency_name' => 'Gorakhpur Rural गोरखपुर ग्रामीण'],
            ['constituency_no' => 324, 'constituency_name' => 'Sahajanwa सहजनवा'],
            ['constituency_no' => 325, 'constituency_name' => 'Khajani खजानी (एससी)'],
            ['constituency_no' => 326, 'constituency_name' => 'Chauri-Chaura चौरी-चौरा'],
            ['constituency_no' => 327, 'constituency_name' => 'Bansgaon बांसगांव (एससी)'],
            ['constituency_no' => 328, 'constituency_name' => 'Chillupar चिल्लूपार'],
            ['constituency_no' => 329, 'constituency_name' => 'Khadda खड्डा'],
            ['constituency_no' => 330, 'constituency_name' => 'Padrauna पडरौना'],
            ['constituency_no' => 331, 'constituency_name' => 'Tamkuhi Raj तमकुही राज'],
            ['constituency_no' => 332, 'constituency_name' => 'Fazilnagar फाजिल नगर'],
            ['constituency_no' => 333, 'constituency_name' => 'Kushinagar कुशीनगर'],
            ['constituency_no' => 334, 'constituency_name' => 'Hata हठ'],
            ['constituency_no' => 335, 'constituency_name' => 'Ramkola रामकोला (एससी)'],
            ['constituency_no' => 336, 'constituency_name' => 'Rudrapur रुद्रपुर'],
            ['constituency_no' => 337, 'constituency_name' => 'Deoria देवरिया'],
            ['constituency_no' => 338, 'constituency_name' => 'Pathardeva पथरदेवा'],
            ['constituency_no' => 339, 'constituency_name' => 'Rampur Karkhana रामपुर कारखाना'],
            ['constituency_no' => 340, 'constituency_name' => 'Bhatpar Rani भाटपर रानी'],
            ['constituency_no' => 341, 'constituency_name' => 'Salempur सलेमपुर (एससी)'],
            ['constituency_no' => 342, 'constituency_name' => 'Barhaj बरहाज'],
            ['constituency_no' => 343, 'constituency_name' => 'Atrauliya अतरौलिया'],
            ['constituency_no' => 344, 'constituency_name' => 'Gopalpur गोपालपुर'],
            ['constituency_no' => 345, 'constituency_name' => 'Sagri सागरी'],
            ['constituency_no' => 346, 'constituency_name' => 'Mubarakpur मुबारकपुर'],
            ['constituency_no' => 347, 'constituency_name' => 'Azamgarh आजमगढ़'],
            ['constituency_no' => 348, 'constituency_name' => 'Nizamabad निजामाबाद'],
            ['constituency_no' => 349, 'constituency_name' => 'Phoolpur Pawai फूलपुर पवई'],
            ['constituency_no' => 350, 'constituency_name' => 'Didarganj दीदारगंज'],
            ['constituency_no' => 351, 'constituency_name' => 'Lalganj लालगंज (एससी)'],
            ['constituency_no' => 352, 'constituency_name' => 'Mehnagar मेहनगर (एससी)'],
            ['constituency_no' => 353, 'constituency_name' => 'Madhuban मधुबन'],
            ['constituency_no' => 354, 'constituency_name' => 'Ghosi घोसी'],
            ['constituency_no' => 355, 'constituency_name' => 'Muhammadabad-Gohna मुहम्मदाबाद-गोहना (एससी)'],
            ['constituency_no' => 356, 'constituency_name' => 'Mau मऊ'],
            ['constituency_no' => 357, 'constituency_name' => 'Belthara Road बेल्थारा रोड (SC)'],
            ['constituency_no' => 358, 'constituency_name' => 'Rasara रसारा'],
            ['constituency_no' => 359, 'constituency_name' => 'Sikanderpur सिकंदरपुर'],
            ['constituency_no' => 360, 'constituency_name' => 'Phephana फेफाना'],
            ['constituency_no' => 361, 'constituency_name' => 'Ballia Nagar बलिया नगर'],
            ['constituency_no' => 362, 'constituency_name' => 'Bansdih बांसडीह'],
            ['constituency_no' => 363, 'constituency_name' => 'Bairia बैरिया'],
            ['constituency_no' => 364, 'constituency_name' => 'Badlapur बदलापुर'],
            ['constituency_no' => 365, 'constituency_name' => 'Shahganj शाहगंज'],
            ['constituency_no' => 366, 'constituency_name' => 'Jaunpur जौनपुर'],
            ['constituency_no' => 367, 'constituency_name' => 'Malhani मल्हनी'],
            ['constituency_no' => 368, 'constituency_name' => 'Mungra Badshahpur मुंगरा बादशाहपुर'],
            ['constituency_no' => 369, 'constituency_name' => 'Machhlishahr मछलीशहर (SC)'],
            ['constituency_no' => 370, 'constituency_name' => 'Mariyahu मारियाहू'],
            ['constituency_no' => 371, 'constituency_name' => 'Zafrabad जाफराबाद'],
            ['constituency_no' => 372, 'constituency_name' => 'Kerakat केराकत (SC)'],
            ['constituency_no' => 373, 'constituency_name' => 'Jakhanian जखानियन (SC)'],
            ['constituency_no' => 374, 'constituency_name' => 'Saidpur सैदपुर (एससी)'],
            ['constituency_no' => 375, 'constituency_name' => 'Ghazipur Sadar गाजीपुर सदर'],
            ['constituency_no' => 376, 'constituency_name' => 'Jangipur जंगीपुर'],
            ['constituency_no' => 377, 'constituency_name' => 'Zahoorabad जहूराबाद'],
            ['constituency_no' => 378, 'constituency_name' => 'Mohammadabad मोहम्मदाबाद'],
            ['constituency_no' => 379, 'constituency_name' => 'Zamania ज़मानिया'],
            ['constituency_no' => 380, 'constituency_name' => 'Mughalsarai मुगलसराय'],
            ['constituency_no' => 381, 'constituency_name' => 'Sakaldiha Sakaldiha'],
            ['constituency_no' => 382, 'constituency_name' => 'Saiyadraja सैयदराजा'],
            ['constituency_no' => 383, 'constituency_name' => 'Chakia चकिया (एससी)'],
            ['constituency_no' => 384, 'constituency_name' => 'Pindra पिंडरा'],
            ['constituency_no' => 385, 'constituency_name' => 'Ajagara अजगरा (एससी)'],
            ['constituency_no' => 386, 'constituency_name' => 'Shivpur शिवपुर'],
            ['constituency_no' => 387, 'constituency_name' => 'Rohaniya रोहनिया'],
            ['constituency_no' => 388, 'constituency_name' => 'Varanasi North वाराणसी उत्तर'],
            ['constituency_no' => 389, 'constituency_name' => 'Varanasi South वाराणसी दक्षिण'],
            ['constituency_no' => 390, 'constituency_name' => 'Varanasi Cantt. वाराणसी छावनी'],
            ['constituency_no' => 391, 'constituency_name' => 'Sevapuri सेवापुरी'],
            ['constituency_no' => 392, 'constituency_name' => 'Bhadohi भदोही'],
            ['constituency_no' => 393, 'constituency_name' => 'Gyanpur ज्ञानपुर'],
            ['constituency_no' => 394, 'constituency_name' => 'Aurai औराई (SC)'],
            ['constituency_no' => 395, 'constituency_name' => 'Chhanbey छानबे (एससी)'],
            ['constituency_no' => 396, 'constituency_name' => 'Mirzapur मिर्जापुर'],
            ['constituency_no' => 397, 'constituency_name' => 'Majhawan मझवान'],
            ['constituency_no' => 398, 'constituency_name' => 'Chunar चुनार'],
            ['constituency_no' => 399, 'constituency_name' => 'Marihan मरिहान'],
            ['constituency_no' => 400, 'constituency_name' => 'Ghorawal घोरावल'],
            ['constituency_no' => 401, 'constituency_name' => 'Robertsganj रोबेर्त्स्गंज'],
            ['constituency_no' => 402, 'constituency_name' => 'Obra ओबरा (एसटी)'],
            ['constituency_no' => 403, 'constituency_name' => 'Duddhi दुद्धी (एसटी)'],
        ];

        foreach ($vidhansabhas as $vidhansabha) {
            Vidhansabha::create($vidhansabha);
        }
    }
}